# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:8080/cinemas/rest/cinemas
Content-Type: application/json

{
  "name": "Arkadia",
  "city": "Warszawa"
}

###

GET http://localhost:8080/cinemas/rest/cinemas
Content-Type: application/json

###

GET http://localhost:8080/cinemas/rest/cinemas/1/suspensions/check?from=10/01/2020 10:00&until=11/01/2020 12:00
Content-Type: application/json

###

GET http://localhost:8080/cinemas/rest/halls/2/suspensions/check?from=05/01/2020&until=05/02/2020
Content-Type: application/json

###

GET http://localhost:8080/cinemas/rest/halls/2
Content-Type: application/json

###

GET http://localhost:8080/cinemas/rest/halls/1/suspensions
Content-Type: application/json

###

POST http://localhost:8080/cinemas/rest/cinemas/1/suspensions
Content-Type: application/json

{
  "from": "01/10/2020 10:00",
  "until": "01/11/2020 12:00"
}

###

DELETE http://localhost:8080/cinemas/rest/cinemas/suspensions/1
Content-Type: application/json

###

GET http://localhost:8080/cinemas/rest/cinemas/1/suspensions
Content-Type: application/json

###

POST http://localhost:8080/cinemas/rest/halls
Content-Type: application/json

{
  "cinemaId": "1",
  "name": "sala-2",
  "layout": [
    {
      "number": "1",
      "elements": [
        {
          "index": 0,
          "number": 1,
          "kind": "SEAT"
        },
        {
          "index": 1,
          "number": 2,
          "kind": "SEAT"
        },
        {
          "index": 2,
          "number": 3,
          "kind": "SEAT"
        }
      ]
    }
  ]
}

###

GET http://localhost:8080/cinemas/rest/halls/1
Content-Type: application/json

###

POST http://localhost:8080/cinemas/rest/halls/2/suspensions
Content-Type: application/json

{
  "from": "01/01/2020 10:00",
  "until": "01/10/2020 12:00"
}

###

GET http://localhost:8080/cinemas/rest/cinemas/1?at=05/01/2020 10:20
Content-Type: application/json

###

POST http://localhost:8080/showscheduler/rest/shows
Content-Type: application/json

{
  "id": "a2f004c4-7f58-40be-8c1f-df1fb186fc7e",
  "movieId": 1,
  "cinemaId": 2,
  "cinemaHallId": 3,
  "start": "24/05/2020 22:30"
}

###
