POST http://localhost:9090/categories
Content-type: application/json

{
  "name": "Jedzenie"
}

###

POST http://localhost:9090/categories
Content-type: application/json

{
  "name": ""
}

###

GET http://localhost:9090/categories?phrase=Je

###

PUT http://localhost:9090/categories/a7efccb4-1a9d-4755-a771-97d1971218be
Content-type: application/json

{
  "name": "Samochody"
}

###

POST http://localhost:9090/products
Content-type: application/json

{
  "name": "Chlebek",
  "categoryId": "5fb3096f-e89f-48f4-818e-fa561dbf70ce",
  "price": "8.90"
}

###

GET http://localhost:9090/products

###

PUT http://localhost:9090/products/6ba02c4e-04ae-4321-bda5-6bb4def03086
Content-type: application/json

{
  "name": "Samochody",
  "categoryId": "b44f88bf-5d4c-4000-9cec-f2d4adecb184",
  "price": 5.60
}

###

POST http://localhost:9090/users
Content-type: application/json

{
  "email": "john.doe@test.com",
  "password": "Test1234"
}

###

POST http://localhost:9090/carts
Content-type: application/json

{
  "productId": "6ba02c4e-04ae-4321-bda5-6bb4def03086"
}

###

GET http://localhost:9090/carts

###

###

PUT http://localhost:9090/carts
Content-type: application/json

{
  "productId": "6ba02c4e-04ae-4321-bda5-6bb4def03086",
  "newQuantity": 6
}

###

DELETE http://localhost:9090/carts
Content-type: application/json

{
  "productId": "6ba02c4e-04ae-4321-bda5-6bb4def03086"
}