POST http://localhost:9090/categories
Content-type: application/json

{
  "name": "Jedzenie"
}
###

POST http://localhost:9090/categories
Content-type: application/json

{
  "name": ""
}
###

GET http://localhost:9090/categories?phrase=Je

###

PUT http://localhost:9090/categories/a7efccb4-1a9d-4755-a771-97d1971218be
Content-type: application/json

{
  "name": "Samochody"
}

###

POST http://localhost:9090/products
Content-type: application/json

{
  "name": "",
  "categoryId": "5fb3096f-e89f-48f4-818e-fa561dbe",
  "price": "-8.90"
}
###

GET http://localhost:9090/products

###

PUT http://localhost:9090/products/bbd8953b-7e3b-4f82-a0d0-0d02e69a2f81
Content-type: application/json

{
  "name": "Samochody",
  "categoryId": "bbd8953b-7e3b-4f82-a0d0-0d02e69a2f81",
  "price": 5.60
}

###

POST http://localhost:9090/users
Content-type: application/json

{
  "email": "john.doe@test.com",
  "password": "Test1234"
}