POST http://localhost:8088/movies
Content-Type: application/json

{
  "title": "Xyz",
  "durationMinutes": 120,
  "directorId": 1,
  "actorIds": [1, 2],
  "genreIds": [3, 4]
}
###

POST http://localhost:8088/movies/sample