#!/bin/bash

set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASS';
  CREATE DATABASE cinemas;
  CREATE DATABASE movies;
  CREATE DATABASE shows;
  CREATE DATABASE reservations;
  GRANT ALL PRIVILEGES ON DATABASE cinemas TO $APP_DB_USER;
  GRANT ALL PRIVILEGES ON DATABASE movies TO $APP_DB_USER;
  GRANT ALL PRIVILEGES ON DATABASE shows TO $APP_DB_USER;
  GRANT ALL PRIVILEGES ON DATABASE reservations TO $APP_DB_USER;
EOSQL